version: '3.8'

services:
  app:
    image: ahiipsa/staking-dashboard-statistic:0.0.3
    restart: always
    depends_on:
      - mongo-service
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: 'mongodb://mongo-service:27017/MyDb'

  mongo-service:
    image: mongo
    restart: always
    logging:
      driver: none
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - 27017:27017
