version: '3.8'

services:
#  app:
#    build:
#      dockerfile: Dockerfile
#    container_name: staking-dashboard.statistic
#    ports:
#      - 3000:3000
#    environment:
#      DATABASE_URL: 'mongodb://mongo-service:27017/MyDb'

  mongo-service:
    image: mongo
    restart: always
    logging:
      driver: none
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - 27017:27017
